### ISSUE TITLE
Cambio en el plugin de gc-kick

### ISSUE THREAD

**Issue by ReyEndymion** [theh2so4/Mystic-Plugins#13]
Necesito un cambio en el comando kick que sea capaz de que cuando se etiqueté al Bot el mismo detecte su eliminación y se despida con una frase antes de salirse

También me gustaría que en el nuevo código que existe en el mystic haya un contador que si quieres te paso el código para que el Bot pueda eliminar cada 20 segundos a un número de una lista de tags y así evitar que se vaya a soporte por dicha eliminación

Es decir una eliminación controlada

**Comment by theh2so4** [comment]
[ ! ] Cambio directo en el codigo de Mystic.
