### ISSUE TITLE
Modo de auto respuesta interactiva

### ISSUE THREAD

**Issue by ReyEndymion** [theh2so4/Mystic-Plugins#14]
Me gustaría un plugin que sea capaz de esperar una respuesta incorrecta o correcta y Que responda a cada caso, es decir si quisiéramos hacer adivinanzas hasta que la persona diga la palabra mágica y la respuesta sea acertada... Esto también serviría para realizar a través de WhatsApp exámenes para la educación, con los botones de lista poderle dar opciones para que respondan a una elección y que de esta manera se evalúa el total de respuestas

También que el plugin tenga un límite de tiempo y que en un solo archivo se pueda realizar varias preguntas con sus respuestas

También me gustaría que dentro de ese mismo código se pueda etiquetar en random a más de 3 personas con el fin de contar una historia o hacer un chiste con los tags

Yo tengo el código preliminar y no sé si te sirva para empezar.... El código preliminar lo puedes obtener en el bot ANI MX SCANS de mi proyecto y se llama el archivo asistentegrupos o asistentegruposrol

Además me gustaría que hubiera la capacidad de evaluar el apodo o tag de la persona con el fin de que depende del nombre de la persona que se haya puesto es que pueda responder en masculino o en femenino algunas frases de bienvenida

**Comment by theh2so4** [comment]
[ ! ] Cambio directo en el codigo de Mystic.
