### ISSUE TITLE
Evaluación de imágenes y videos

### ISSUE THREAD

**Issue by ReyEndymion** [theh2so4/Mystic-Plugins#15]
No sé si sea posible utilizar el modo OCR del bot para evaluar imágenes e inclusive evaluar lo que digan dentro las imágenes para saber si una imagen o un video tiene escenas eróticas y que conforme a esa evaluación el bot pueda eliminar a alguien de un grupo en donde no está permitido ese tipo de imágenes o vídeos Qué es prácticamente en la gran mayoría de los grupos que en sus reglas ponen ese comentario

**Comment by theh2so4** [comment]
[ ! ] Cambio directo en el codigo de Mystic.
